### ISSUE TITLE
Automate Deployment to GitHub Pages.

### ISSUE THREAD

**Issue by kaykeeb3** [boss3g/deploy-example#7]
Implement a GitHub Actions workflow to automate the deployment process for the website to GitHub Pages. This workflow should trigger on pushes to the `main` branch and handle the following:  

1. Check out the repository.  
2. Deploy the build output located in the `./public` directory to the `gh-pages` branch.  
3. Notify when the deployment is successful.  

Acceptance Criteria:  
- The workflow file is added and configured correctly.  
- Deployment runs without errors and publishes the site to GitHub Pages.  
- Clear notification of success is provided in the workflow logs.

**Comment by kaykeeb3** [comment]
Example of suggested improvements:

```
name: Deploy to GitHub Pages

# Whenever changes are pushed to the main branch.
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Define the environment where the job will run
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
          publish_branch: gh-pages  # Branch where the site will be published
          publish_dir: ./public    # Directory containing the build output

      # Step 3: Notify deployment success
      - name: Notify deployment success
        if: success()  # Ensure this step runs only if the deployment succeeds
        run: echo "🚀 Deployment to GitHub Pages was successful!"
```
